### ISSUE TITLE
Unable to start the project on my server, page is not loading

### ISSUE THREAD

**Issue by vikujangid** [gramps-project/Gramps.js#291] opened 2023-10-05 12:38 UTC
My Server is Ubuntu 23 from Digital Ocean with 4GB RAM and 80GB SSD

I followed this document
https://www.grampsweb.org/dev-frontend/setup/

```
git clone git@github.com:gramps-project/Gramps.js.git
cd Gramps.js
```

And after that I ran docker compose command in this fresh server
```
docker-compose up -d
```

Initially I got some errors like `problem in creating users (something related to database connections)` by these errors were skipped and docker compose was successful. 

When I open browser and try to open my server IP address (on 80 port), it automatically redirects http to https. But the docker compose opens only 80 port and now auto redirect leads to 443 port which is not open. 

---
When I tried https://<< my-ip-address >>:5555 it opens the a web page which was trying to load for 10-20 seconds and then it shows only blank page with browser title bar titled with "Gramps Web". But the page is completely blank

I'm not sure how to fix it. Do I need to setup backend first? And how to link it with this frontend? Please help me. 
Thanks in advance

**Comment by DavidMStraub** [comment] 2023-10-05 12:42
Hi,

the development setup is unfortunately currently not working, but this is tracked in #213.

If nobody is able to fix this issue, we might have to change the documentation (I am not myself using the docker-based dev setup).

I will still close this as a duplicate of #213.

**Closed by DavidMStraub** 2023-10-05 12:42 UTC

**Comment by vikujangid** [comment] 2023-10-05 14:13
@DavidMStraub  Thank you for reply.. 

But mine issue is different than [#213](https://github.com/gramps-project/Gramps.js/issues/213).  In my case docker has been started but page is not loading.

**Comment by DavidMStraub** [comment] 2023-10-05 14:17
The instructions you meant are for local development of the Gramps Web frontend, not for deployment on a server. What are you trying to achieve here?
