### ISSUE TITLE
enable smtp config and test on administration page

### ISSUE THREAD

**Issue by JohnRDOrazio** [gramps-project/Gramps.js#328] opened 2023-12-11 01:26 UTC
it would be useful to be able to set the smtp configurations from the administration page, reserving these settings for the Owner / Administrator roles. And it would be useful to be able to test the configuration right away, with some visual feedback if everything is working correctly (or error feedback if something is not working correctly).

**Comment by DavidMStraub** [comment] 2023-12-11 07:24
Yes, but closing as duplicate of #165.

**Closed by DavidMStraub** 2023-12-11 07:24 UTC
