### ISSUE TITLE
Server Responds with Error 422: Unprocessable Entity on Setup

### ISSUE THREAD

**Issue by psacawa** [gramps-project/Gramps.js#101] opened 2022-09-10 22:56 UTC
To reproduce:

1. Make a basic setup with  `docker-compose` behind `nginx` with certbot  TLS as follows:

```
# docker-compose.yml
version: "3.7"

services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "5000:5000"  # host:docker
    environment:
      TREE: "Gramps Web"  # will create a new tree if not exists
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
```

```
# /etc/nginx/sites-enabled/gramps
server {
        server_name genealogia.sacawa.net;

        location / {
                proxy_pass http://127.0.0.1:5000/$uri;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/genealogia.sacawa.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/genealogia.sacawa.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = genealogia.sacawa.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80 default_server;
        server_name genealogia.sacawa.net;
    return 404; # managed by Certbot


}
```
Let's encrypt was added for `genealogia.sacawa.net` via  Let's Encrypt Certbot.

2. Go to setup the server, uploading `.xml` file.

3. Try to set the language as shown below, getting 422 error from server, generated by very weird-looking HTTP request.

Here is a video of the bug: [https://sacawa.net/static/video/gramps-bug.mkv](https://sacawa.net/static/video/gramps-bug.mkv)

**Comment by psacawa** [comment] 2022-09-10 23:53
In `docker-compose` output:

```
Creating network "gramps_default" with the default driver
Creating gramps_grampsweb_1 ... done
Attaching to gramps_grampsweb_1
^[grampsweb_1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
grampsweb_1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
grampsweb_1  | [2022-09-10 23:48:42 +0000] [11] [INFO] Starting gunicorn 20.1.0
grampsweb_1  | [2022-09-10 23:48:42 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
grampsweb_1  | [2022-09-10 23:48:42 +0000] [11] [INFO] Using worker: sync
grampsweb_1  | [2022-09-10 23:48:42 +0000] [12] [INFO] Booting worker with pid: 12
grampsweb_1  | [2022-09-10 23:48:42 +0000] [13] [INFO] Booting worker with pid: 13
grampsweb_1  | [2022-09-10 23:48:42 +0000] [14] [INFO] Booting worker with pid: 14
grampsweb_1  | [2022-09-10 23:48:42 +0000] [15] [INFO] Booting worker with pid: 15
grampsweb_1  | [2022-09-10 23:48:42 +0000] [16] [INFO] Booting worker with pid: 16
grampsweb_1  | [2022-09-10 23:48:42 +0000] [17] [INFO] Booting worker with pid: 17
grampsweb_1  | [2022-09-10 23:48:42 +0000] [18] [INFO] Booting worker with pid: 18
grampsweb_1  | [2022-09-10 23:48:42 +0000] [19] [INFO] Booting worker with pid: 19
grampsweb_1  | Unable to init server: Could not connect: Connection refused
grampsweb_1  | Unable to init server: Could not connect: Connection refused
```

**Comment by DavidMStraub** [comment] 2022-09-11 13:56
Hi,

thanks, that's interesting. I am not sure what is causing it. Could you please check in your browser dev tools in the Local Storage, what is has as language key in the settings object?

<img width="851" alt="image" src="https://user-images.githubusercontent.com/10965193/189531370-ba3ab256-6915-4ef2-9866-9daad342f522.png">

**Comment by DavidMStraub** [comment] 2022-09-11 13:58
Also, can you please try with German or Swedish as language? It might be related to our new treatment of "frontend-only" strings, and those are still missing for Polish/Hungarian.

**Comment by DavidMStraub** [comment] 2022-09-11 14:09
... and finally, can you please double-check you are running the latest image? Because the fact that the button is greyed out looks like https://github.com/gramps-project/Gramps.js/issues/84 which should already be fixed...

**Comment by psacawa** [comment] 2022-09-13 14:23
The problem is present for all languages it seems, including English and German. Moreover the localstorage contents seems normal: 

```
grampsjs_settings:  {"lang":"de"}
```

The image was the one with `latest`  tag on `ghcr.io/gramps-project/grampsweb` per `docker-compose.yml`. It should be up to date 

```
$ sudo docker pull ghcr.io/gramps-project/grampsweb:latest
latest: Pulling from gramps-project/grampsweb
Digest: sha256:3658217c9fc6539a492db11753d10489025c2e0a34d0b3205c50d4ffc927d5e5
Status: Image is up to date for ghcr.io/gramps-project/grampsweb:latest
ghcr.io/gramps-project/grampsweb:latest
```

In any case I leave [genealogia.sacawa.net](genealogia.sacawa.net) on if you care to look at it. I will take a look at the failed connection in backend, as this seems like a more likely suspect.

**Comment by DavidMStraub** [comment] 2022-09-13 14:32
I suspect it's just this: https://github.com/gramps-project/gramps-webapi/issues/225

Can you please check whether your NGINX imposes a max length on the request string?

**Comment by DavidMStraub** [comment] 2022-09-13 15:43
Ok thanks for checking. Wondering what else it could be 🤔

**Comment by DavidMStraub** [comment] 2022-09-13 19:54
So I just tried the most minimal example:

```bash
docker run -p "5055:5000" -e TREE=new ghcr.io/gramps-project/grampsweb:latest
```

This starts an empty Gramps Web at http://localhost:5055.

I created an owner account and uploaded the `example.gramps` Gramps example XML file.

Then I selected Polish as language and set a home person. There was no error.

So the problem must either be with your proxy setup or with your tree.

Can you please try the above minimal example with your tree, as well as your own set up with the Gramps example tree, to find out the cause?

**Comment by DavidMStraub** [comment] 2022-09-24 18:42
Did you find out anything?

**Comment by psacawa** [comment] 2022-09-26 15:15
I have some time to look at it tonight, I will let you know. So far I get the same result as before.

**Comment by DavidMStraub** [comment] 2022-10-21 11:33
Will close this. Feel free to reopen if the issue persists with the minimal example.

**Closed by DavidMStraub** 2022-10-21 11:33 UTC
